### ISSUE TITLE
Cannot invoke "java.io.File.mkdirs()" because the return value of "java.io.File.getParentFile()" is null

### ISSUE THREAD

**Issue by fallen** [OndraZizka/junitdiff#14]
Hello, 
I get this stack trace:

```
fallen@fallen-ThinkPad-X260:~/dev/junitdiff-2.0.0$ java -jar JUnitDiff-2.0.0-executable.jar /home/fallen/dev/uclibc-ng-ci/artifacts/armv7/junit_report.xml  -o prout.html
20:50:01.951 [main] DEBUG ch.zizka.junitdiff.JUnitDiffApp - Starting JUnitDiff - multiple JUnit test runs comparing tool.
20:50:02.019 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Parsing test reports group '/home/fallen/dev/uclibc-ng-ci/artifacts/armv7/junit_report.xml': 1 files.
20:50:02.193 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Aggregating test results - group: /home/fallen/dev/uclibc-ng-ci/artifacts/armv7/junit_report.xml - 1 test suites.
20:50:02.219 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Exporting to InvocationParams(inputPaths=[/home/fallen/dev/uclibc-ng-ci/artifacts/armv7/junit_report.xml], outPath=prout.html, outputFormat=HTML, toStdOut=false, title=null).outPath
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.mkdirs()" because the return value of "java.io.File.getParentFile()" is null
	at cz.dynawest.xslt.XsltTransformer.transform(XsltTransformer.kt:63)
	at ch.zizka.junitdiff.export.XmlExporter.exportToHtmlFile(XmlExporter.kt:33)
	at ch.zizka.junitdiff.JUnitDiffApp.runApp(JUnitDiffApp.kt:96)
	at ch.zizka.junitdiff.JUnitDiffApp.access$runApp(JUnitDiffApp.kt:23)
	at ch.zizka.junitdiff.JUnitDiffApp$Companion.main(JUnitDiffApp.kt:136)
	at ch.zizka.junitdiff.JUnitDiffApp.main(JUnitDiffApp.kt)

```

I attach my junit report file here: 
[junit_report.xml.gz](https://github.com/OndraZizka/junitdiff/files/13064302/junit_report.xml.gz)

**Comment by abbas-gadhia** [comment]
Getting a similar error

```
ab@ThinkPad-P14s-Gen-2a:~/temp/delme-$ junitdiff ut/spark35/target/surefire-reports -o op
21:32:45.193 [main] DEBUG ch.zizka.junitdiff.JUnitDiffApp - Starting JUnitDiff - multiple JUnit test runs comparing tool.
21:32:45.324 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Parsing test reports group 'spark35/target/surefire-reports': 258 files.
21:32:46.896 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Aggregating test results - group: spark35/target/surefire-reports - 258 test suites.
21:32:46.948 [main] INFO ch.zizka.junitdiff.JUnitDiffApp - Exporting to InvocationParams(inputPaths=[spark35/target/surefire-reports], outPath=op, outputFormat=HTML, toStdOut=false, title=null).outPath
Exception in thread "main" java.lang.NullPointerException
	at cz.dynawest.xslt.XsltTransformer.transform(XsltTransformer.kt:63)
	at ch.zizka.junitdiff.export.XmlExporter.exportToHtmlFile(XmlExporter.kt:33)
	at ch.zizka.junitdiff.JUnitDiffApp.runApp(JUnitDiffApp.kt:96)
	at ch.zizka.junitdiff.JUnitDiffApp.access$runApp(JUnitDiffApp.kt:23)
	at ch.zizka.junitdiff.JUnitDiffApp$Companion.main(JUnitDiffApp.kt:136)
	at ch.zizka.junitdiff.JUnitDiffApp.main(JUnitDiffApp.kt)
```
